name: Build SPT Launcher

on:
  workflow_dispatch:

jobs:
  job2:
    name: Build Windows SPT Launcher
    strategy:
      fail-fast: false
      matrix:
        versions:
          [
            {
              lbranch: "4.0.0-DEV",
              dotnet: 9,
            }
          ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{matrix.versions.dotnet}}

      - name: Build SPT Launcher
        id: build_launcher
        shell: pwsh
        run: ./build_launcher.ps1 -Overwrite -Branch ${{ matrix.versions.lbranch }}

      - name: Get Launcher Commit Hash
        id: get_hash
        shell: bash
        run: echo "hash=$(git -C ./Launcher rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload Launcher Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SPT-Launcher-${{ matrix.versions.lbranch }}-${{ steps.get_hash.outputs.hash }}
          path: './Launcher/project/Build/*'
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 3
          compression-level: 9
